### ISSUE TITLE
BUG - If There's an Error Retrieving Policy - Still Able to Switch Tabs on Policy Page - Doing so Returns Blank Screen + Error

### ISSUE THREAD

**Issue by werzl** [filetrust/icap-management-ui#100]
![image](https://user-images.githubusercontent.com/16911902/100902718-11618880-34bd-11eb-8c53-5c25c2b7be37.png)

**Comment by asloman** [comment]
Checked on local deployment of management ui

Reproduction steps:
- Navigate to policy page on management ui
- In Network tools (f12 in browser) block "current" fetch request
- Navigate away and back to policy page
-  Click "Current" Tab

Expected Results: The error message "Error getting Policy data" is displayed". This also applies if swapping to "History" tab

Actual Results: The error message "Error getting Policy data" is displayed". This also applies if swapping to "History" tab

This was expected functionality, confirmed with @werzl 

Full testing of ui will be done once deployed to cluster.
