### ISSUE TITLE
UI Bug:  The Risk for unknown files are not displayed

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/icap-management-ui#118]
If a unknown file type is sent through Icap for processing. the outcome is correct based on the defined routing policy but the policy applied is not displayed.

To replicate:
Go to: http://management-ui.uksouth.cloudapp.azure.com >> policy
Set the routing policy for un-processable file types to block
Send a GW un-processable file type through endpoint -- icap-client-main.uksouth.cloudapp.azure.com
Go to http://management-ui.uksouth.cloudapp.azure.com >> request-history
Search list using the 1 hour period selection

Expected: 
The file should be visible with the risk shown as: Blocked by policy

Actual:
The file should is visible but the risk field is blank

![2021-01-05_15h34_34](https://user-images.githubusercontent.com/61200359/103667536-faa3cb00-4f6d-11eb-9074-91f230a1b792.png)

**Comment by tstepany** [comment]
As per Nadege QA spreadsheet this bug is high priority for them so changing from P2 to P1

**Comment by asloman** [comment]
Clarified what is expected, if the file type is unknown then the risk will also be unknow (as of 15/01/2021)

Steps Followed:
Process an unprocessable file through the icap server
Log into ui, then navigate to request history

Expected Result:
The processed file is returned as file type "unknown" and risk "unknown"

Actual Result:
The processed file is returned as file type "unknown" and risk "unknown"
