### ISSUE TITLE
BUG - When the Policy Management Api is down, the Policy Page is Blank When Navigating to the Current Policy Tab

### ISSUE THREAD

**Issue by werzl** [filetrust/icap-management-ui#120]
## To Replicate
- Login to the UI
- Navigate to the Policy View
- Ensure the Policy Management Api is unreachable, or the management UI server returns an error on GET /policy/draft
- Click the 'Current' tab in the Policy View

**Comment by asloman** [comment]
Checked on local deployment of management ui.

Steps followed:
Login to the UI
Navigate to the Policy View
Ensure the Policy Management Api is unreachable, or the management UI server returns an error on GET /policy/draft
Click the 'Current' tab in the Policy View

Expected Results: The "Current" tab displays the message "Error getting policy data." the same as on the "Draft" Tab

Actual Results: The "Current" tab displays the message "Error getting policy data." the same as on the "Draft" Tab
