### ISSUE TITLE
Management UI- Request History: Processed files are not visible 

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/icap-management-ui#124]
To replicate:
Using the icap client, process a file through the Icap server (used endpoint is: icap-client-main.uksouth.cloudapp.azure.com on port 1344)
Login to the UI (used in test is: http://management-ui.uksouth.cloudapp.azure.com/)
Go to Request History
Filter the log using the 1 hour period
The expected result is:  The file transaction record is visible 
The actual result is: The list is blank for any time period selection

![2021-01-07_14h04_10](https://user-images.githubusercontent.com/61200359/103901707-6498ad80-50f1-11eb-8ed2-a6cbbd0f217d.png)

![2021-01-07_14h03_07](https://user-images.githubusercontent.com/61200359/103901718-69f5f800-50f1-11eb-9082-172553462c3e.png)

The pods: event-submission-service and  icap-administration-service-qa-main-policy-api are in status: CrashLoopBackOff

See logs below for more details:

![event-submission-service log](https://user-images.githubusercontent.com/61200359/103900463-bc361980-50ef-11eb-8c9a-03b0265c24d4.png)
[qa-main policy api and event submission service pods statuses.txt](https://github.com/filetrust/icap-management-ui/files/5781957/qa-main.policy.api.and.event.submission.service.pods.statuses.txt)

**Comment by gw-sbirch** [comment]
@nadege please retest, the password on the backend was causing the issue.

http://management-ui-qa.uksouth.cloudapp.azure.com
icap-client-qa-main.uksouth.cloudapp.azure.com

**Comment by asloman** [comment]
Checked on uk south qa.

Reproduction Steps:
Using the icap client, process a file through the Icap server (used endpoint is: icap-client-qa-main.uksouth.cloudapp.azure.com on port 1344)
Login to the UI (used in test is: http://management-ui-qa.uksouth.cloudapp.azure.com)
Go to Request History
Filter the log using the 1 hour period

The expected result is: The file transaction record is visible

Actual result:  The file transaction record is visible
