### ISSUE TITLE
The Adaptation policy is not being applied correctly to submitted files

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/icap-management-ui#134]
A file containing a disallowed content flag processed through the Icap server is not blocked

To replicate:
Go to: http://management-ui-qa.uksouth.cloudapp.azure.com/ or http://management-ui.northeurope.cloudapp.azure.com/
Set all policy flags for word to disallow
Set the NCFS Glasswall blocked files to Block
Submit a file containing one or more of the content flags using the Icap client tool on UK south or North endpoint 

Expected:
The file is blocked

Actual:
The file is processed and appears safe on the UI

![2021-01-12_20h09_49](https://user-images.githubusercontent.com/61200359/104367042-2563c580-5512-11eb-9153-046ca28437a5.png)

![2021-01-12_19h38_58](https://user-images.githubusercontent.com/61200359/104367084-390f2c00-5512-11eb-864e-2f08958acac4.png)

![2021-01-12_19h38_36](https://user-images.githubusercontent.com/61200359/104367052-2a287980-5512-11eb-9395-3cf40ea0474b.png)

**Comment by tstepany** [comment]
Seb looking into this.

**Comment by gw-sbirch** [comment]
@NadHodeGW Please sync adaptation and administration namespaces in the QA cluster then retest. (Give me a message if you want me to sync it)

I believe the issue was the fact that Disallow was throwing an exception when trying to distribute the policy in the back end. That is a separate process. Policy Update Service and the Policy Management API logs should show when syncing policy occurs. (and any errors)

**Comment by asloman** [comment]
Hi @gw-sbirch I will be testing this! Please could you sync them for me? Or guide me how to do it?

**Comment by asloman** [comment]
Tested on uk-south endpoints.

Steps followed:
Go to: http://management-ui-qa.uksouth.cloudapp.azure.com/ 
Set all policy flags for word to disallow
Set the NCFS Glasswall blocked files to Block
Submit a file containing one or more of the content flags using the Icap client tool on UK south

Expected Results: 
The file is blocked

Actual Results:
The file is blocked

![2021-01-13_16h45_15](https://user-images.githubusercontent.com/61416937/104482320-b7c1a300-55be-11eb-8b34-14c4760616bb.png)

![2021-01-13_16h45_32](https://user-images.githubusercontent.com/61416937/104482363-c1e3a180-55be-11eb-856e-33b5a4aa7d97.png)

![2021-01-13_16h45_43](https://user-images.githubusercontent.com/61416937/104482396-cb6d0980-55be-11eb-83c8-281f87f99050.png)
