### ISSUE TITLE
Add Sorting By File ID to the Request History Transaction Log

### ISSUE THREAD

**Issue by werzl** [filetrust/icap-management-ui#135]
"is there an Issue in the backlog to add Transaction ID filtering to the Event History Page?? If not, could we add one? It would be useful for Administrators to search on this item."

**Comment by asloman** [comment]
Checked on local deployment of management UI.

Steps followed:
Logged into ui and navigated to request history page
Selected Add Filter > File ID and added a file ID
Pressed okay

Expected results: The page is filtered to only show the file ID that was filtered by
Actual results: The page is filtered to only show the file ID that was filtered by

I have also tried adding multiple File ID's, and for every ID that is added, you will be able to observe that line (if it exists in the time frame selected)
