### ISSUE TITLE
Transactions missing from the request history page

### ISSUE THREAD

**Issue by asloman** [filetrust/icap-management-ui#138]
Completed Transactions are missing from the request history page. Found one way to reproduce, however does not appear to be only way.

Reproduction Steps:

Navigate to ui
Change NCFS policy for Blocked files and unprocessable file, and set all word adaptation policies to "Disallow"
Publish policy
Process a word file
After file processes, navigate to request history page
Expected Results: The file can be observed in the request history

Actual Results: There is no line for the file on the request history page

The above happens on the uk south endpoints. There were no errors in the logs that I could see, and all pods are running. The missing lines are also in the file store.

Missing File_ID's for reference:
9da90c1f-9505-4d10-80c9-4ed9273c4e55 09:13 UKS
2c205301-b248-4994-944b-414661d8df82 15:04 UKS
5e933963-febd-4717-a44f-721e149732a6 11:37 NEU (this one happened not following the steps above)

**Comment by tstepany** [comment]
To wait for synch logs .

**Comment by tstepany** [comment]
Include it in test acceptance report.

**Comment by gw-sbirch** [comment]
Using the steps above i was able to process the file and have it appear in the log: 

![image](https://user-images.githubusercontent.com/60774443/105828838-86cc6f80-5fbb-11eb-83e0-a5a80163944a.png)

I believe this may have already been fixed @asloman 

Was there a particular NCFS policy combination that is required for this bug to occur?

**Comment by asloman** [comment]
Tested on https://management-ui-test-01.uksouth.cloudapp.azure.com/request-history, sending files through icap-client-test-01.uksouth.cloudapp.azure.com.

Still getting same issue as above, however just processing the files by themselves with policy set to sanitise, sending docx.
Some files are returning blank metadata (de565c99-aaf0-4f6a-897b-c7c49037e8d4, df2c3302-bde1-49fb-9d0c-5b4f0d2dc4af) 
Some files are not returning on request history page (39a60e43-9d30-4e71-909b-7dcddcf05a65,df2c3302-bde1-49fb-9d0c-5b4f0d2dc4af
Some files missing event IDs from the metadata file (39a60e43-9d30-4e71-909b-7dcddcf05a65)

All files in brackets were processed on 27/01/2021 between 15:00 and 16:00.

**Comment by asloman** [comment]
Issue also occurs on develop cluster.

Files will intermittently appear. Files get processed correctly, and appear in rebuild logs, but then aren't passed to the event submission service.

Repeating the steps above (changing the ncfs policy/changing policy), sometimes the error message below is produced, and after that no transactions make it to the event-submission-service.
![2021-01-28_20h27_27](https://user-images.githubusercontent.com/61416937/106194835-3e71a500-61a7-11eb-905c-b39b5116b464.png)

**Comment by gw-sbirch** [comment]
@asloman have we seen any more of these since matt added a retry to the event submissions service (Friday)

**Comment by gw-sbirch** [comment]
After discussion with @asloman, we have not seen this pop up since. Closing as it appears to have been fixed.
