### ISSUE TITLE
Resquest History: The Sanitisation & Remedy items sections are not available on the file details screen

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/icap-management-ui#158]
The file details screen shows Error Getting Transactions on Chrome and is blank on Firefox

Using Chrome browser go to https://management-ui-test-01.uksouth.cloudapp.azure.com/
Navigate to Request History
Open a transaction record

![image.png](https://images.zenhubusercontent.com/5f315efe0e4f4158677aea6e/82b9bbc9-994b-47f2-86e9-57cc7fc06153)

Also Using Firefox, the sanitisation & remedy items sections are not available

Comparison of Chrome & Firefox view(chrome left, ff on right
![image](https://user-images.githubusercontent.com/61200359/106015361-53224000-60b6-11eb-9b0d-92716f2d148a.png)

**Comment by asloman** [comment]
Checked on https://management-ui-develop.uksouth.cloudapp.azure.com/request-history

Steps Followed:
Navigate to https://management-ui-develop.uksouth.cloudapp.azure.com/request-history
Click on file

Expected Results: Can observe any issue items that the file has
Actual Results: Can observe any issue items that the file has

![2021-01-29_15h24_29](https://user-images.githubusercontent.com/61416937/106293582-16854e80-6246-11eb-8b22-f34e952ef862.png)
