### ISSUE TITLE
Test: I am able to change the date range of the files displayed using the time intervals

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/icap-management-ui#17]
**Test1-**
**Scenario:** I am able to change the date range of the files displayed using the time intervals
**Precondition:** I am logged in and on the request history page
**Steps:**   
       When I click dateTime and select a <timeInterval>--PASSED
        Then the start date range is updated to <datetimeFrom> and the end date range as <datetimeTo>--PASSED
        And the files processed for the selected period are displayed--FAILED, no data returns when using 1 hour

**Issues on the Request date pickers:**
**1-filter by 1 hour:**
There is data available between now and the previous hour but nothing returns
![2020-10-27_10h20_59](https://user-images.githubusercontent.com/61200359/97292474-32daaf00-1843-11eb-89a2-8dbfcd81086d.png)

**Test2-**
**Scenario**: I can filter the request log using the date picker
        When I select a valid <datetimeFrom> and <datetimeTo>
        Then the files processed for the selected period are displayed--FAILED
All the date ranges tried returned nothing(ex: 27/10/2020 00:59:07 to 27/10/2020 09:47:44) 
![2020-10-27_10h52_10](https://user-images.githubusercontent.com/61200359/97292570-4e45ba00-1843-11eb-8fcb-25ab115f2b1e.png)

**Test3-**
**Scenario**: I am able to filter the log by file risks 
        When I click on the Add Filter button and add a risk filter as <filter>
        Then the result list only shows filtered files with the selected risk ---PASSED

**Test4-**
**Scenario**: I am able to filter the log by file type 
        When I click on the Add Filter button and add a file type filter as <filter>
        Then the result list only shows filtered file type as ---PASSED

**Test5-**
**Scenario**: I am able to filter the log by file id
        When I click on the Add Filter button and add a filter by file ID as <filter>
        Then the result list only shows the filtered file as <filteredFile>---FAILED (not implemented yet--to be retested)
The Add button doesn't work yet

**Comment by werzl** [comment]
> Hi @werzl , 
> 
> Still issues with the time interval selector:  When 1 hour or 12 time interval is selected, no data returns, 
> 
> There is data available and selecting 24hours works ok.

Hi Nadege Is the result "No data" or is it an error where it doesn't load

**Comment by NadHodeGW** [comment]
No data, 
This issue is raised to the transaction-event-api repo: #17
