### ISSUE TITLE
UI-User Management:  Duplicate Emails accepted 

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/icap-management-ui#182]
Login to: management-ui-develop.uksouth.cloudapp.azure.com and go to Users
Add a new user with a email address already used
Click Save Changes

Expected:
There should be a notification error preventing a duplicate email be used
The user details are not saved

Actual:
The user details are saved

**Comment by gw-sbirch** [comment]
Please retest with latest version

Here is the release (main): https://github.com/filetrust/identity-management-service/releases/tag/v0.3.0

**Comment by gw-sbirch** [comment]
@NadHodeGW

**Comment by werzl** [comment]
@gw-sbirch @NadHodeGW - moving this back to in progress - going to update this in the UI to bubble an error up when trying to create a new user with an existing email address.

**Comment by asloman** [comment]
Tested on https://management-ui-develop.uksouth.cloudapp.azure.com/

Steps followed:
Log into ui
Navigate to Users page
Add a new user that has the same email as another user (but different other entries)

Expected Results: Unable to add user and an error message is produced

Actual Results: Unable to add user and an error message is produced

![2021-02-03_15h15_28](https://user-images.githubusercontent.com/61416937/106768194-9854ed80-6633-11eb-96c1-3154ff8f92ad.png)
