### ISSUE TITLE
UI Analytics-- The Analytics View is blank for a period with no transactions

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/icap-management-ui#184]
When the Analytics view is opened for a period without transactions, the notification: 'No Metrics Found' is displayed but appears in the far left upper corner of the screen

The page will need to be refreshed and the default view (Analytics for last hour) is displayed -- waiting to retest when no transactions are available within last hour. 

To replicate:
Go to and Analytics when there are no transactions available for the last hour
Or use the date picker to select a date ex: 29th to 30th if the date picker is available

Expected:
The view shows 'TOTAL FILES PROCESSED' as 0
The file process graph should be displayed with no trend

Actual:
A blank screen is displayed with the notification: 'No Metrics Found' in the far left upper corner of the screen
![Capture2](https://user-images.githubusercontent.com/61200359/106512180-2a8cb280-64c9-11eb-9dfc-7ba73fdd6bf4.PNG)

**Comment by werzl** [comment]
@NadHodeGW 
When encountering a period with no files:
- The 'Total Files Processed' counter should now appear with a value of 0.
- Should still be able to select the date/time on the filter.

Merged to develop

**Comment by werzl** [comment]
**Docker Image Tag:** develop-6417434

**Comment by asloman** [comment]
Checked on https://management-ui-develop.uksouth.cloudapp.azure.com/

Steps Followed:
Log into UI
Navigate to Analytics
On the date time picker, select a time where 0 files have been processed

Expected Results: The page loads, and displays a box of "Files processed:0"

Actual Results: The page loads, and displays a box of "Files processed:0"

![2021-02-03_16h32_44](https://user-images.githubusercontent.com/61416937/106778033-72cce180-663d-11eb-8b8f-b9544bf7717a.png)
