### ISSUE TITLE
Request History: File type filter for PDF and RTF not applying correctly

### ISSUE THREAD

**Issue by asloman** [filetrust/icap-management-ui#190]
The File type filters of PDF and RTF are not correctly applying to the request history.

Tested on both https://management-ui-develop.uksouth.cloudapp.azure.com/ and https://management-ui-qa.uksouth.cloudapp.azure.com/

Reproduction steps:
Log into UI
Navigate to Request History
Add filters "PDF" and "RTF"

Expected Results: The Request History will only display files with the filetypes PDF and RTF

Actual Results: The Request History will display all filetypes

UK South QA:
![2021-02-03_15h41_10.png](https://images.zenhubusercontent.com/5f3d07cddacb511232da95f0/88441f47-fcf4-48c4-bf54-528308f98af6)

UK South Dev:
![2021-02-03_15h41_18.png](https://images.zenhubusercontent.com/5f3d07cddacb511232da95f0/19f113a7-5452-4e83-a40e-c3f85bca2f64)

**Comment by werzl** [comment]
**Docker Image Tag:** develop-eee0f6c

- RTF and PDF filters should now work
- ALL Filters are now disabled while data is loading in the transaction log

**Comment by werzl** [comment]
@asloman

**Comment by asloman** [comment]
Tested on https://management-ui-develop.uksouth.cloudapp.azure.com/

Steps followed:
Log into ui
Navigate to Request History
Add filters "PDF" and "RTF"

Expected Results: The Request History will only display files with the filetypes PDF and RTF

Actual Results: The Request History will only display files with the filetypes PDF and RTF

No filters applied:
![2021-02-04_09h37_55](https://user-images.githubusercontent.com/61416937/106873730-a7d44500-66cc-11eb-9879-94ad3a4984d7.png)

Filters Applied:
![2021-02-04_09h38_18](https://user-images.githubusercontent.com/61416937/106873775-b6226100-66cc-11eb-865c-fd34212392f6.png)
