### ISSUE TITLE
[ICAP Server Offline Deployment ESXI] Logs keep on popping on the screen

### ISSUE THREAD

**Issue by MaNe2020** [filetrust/icap-management-ui#238]
ICAP OVA: s3://glasswall-sow-ova/vms/icap-server/icap-server-c5213deac41f135bface4a1f44d59b69706c1663-124.ova

Video: https://www.loom.com/share/d4797c29b4ed48efb131d9e18e16c834

**Comment by GINAGC** [comment]
Please move defect to https://github.com/k8-proxy/icap-infrastructure, this is not management UI

**Comment by GINAGC** [comment]
Moved to https://github.com/k8-proxy/icap-infrastructure/issues/66
