### ISSUE TITLE
Add Policy History list

### ISSUE THREAD

**Issue by dariovillalon** [filetrust/icap-management-ui#49]

**Comment by NadHodeGW** [comment]
Tested on: http://management-ui.northeurope.cloudapp.azure.com/policy

A new history record is created when a new Draft Policy has been saved & published 
A new history record is created when a new one has been published 
The timestamp displayed against a history record is the time it was published/activated
When a history policy is activated the record is no longer displayed in the history list

The application to files to be tested separately
