### ISSUE TITLE
Update Request History React component to use data from the API

### ISSUE THREAD

**Issue by tstepany** [filetrust/icap-management-ui#5]
Milesonte: Brute Force
Transaction Events: Events List View
Update Request History React component to use data f?rom the API

**Comment by werzl** [comment]
This can be tested along with #1

**Comment by werzl** [comment]
This is has been pushed to QA @NadHodeGW

**Comment by NadHodeGW** [comment]
Tested unsuccessfully but its due to a problem with the api returning data; a new issue is raised to the transaction-event-api repo: #17 for date picker not returning the correct data;
Other issues will be raised individually as found
