### ISSUE TITLE
Update File Info component to use data from the API

### ISSUE THREAD

**Issue by tstepany** [filetrust/icap-management-ui#6]
Milestone : Enterprise Deployment
https://glasswall.atlassian.net/browse/FEATURE-670
Transaction Events: Transaction Details View
Update File Info component to use data from the API

**Comment by werzl** [comment]
This has been pushed to Dev but NOT to QA @NadHodeGW

**Comment by NadHodeGW** [comment]
This has been tested successfully locally on qa branch http://localhost:8080/request-history
A file record can be opened and show details such as: 
Timestamp | Unique File ID | Detected File Extension | Risk (Transaction), Issue Items table list and count, Remedy Items table list and count
