### ISSUE TITLE
BUG - Request History calls GetTransactions twice on load

### ISSUE THREAD

**Issue by werzl** [filetrust/icap-management-ui#77]

**Comment by asloman** [comment]
Checked on http://management-ui.northeurope.cloudapp.azure.com/request-history. Only one request being generated now. Checked 1 hour, 12 hour, 24 hour, and custom.
![2020-12-02_16h01_48](https://user-images.githubusercontent.com/61416937/100897553-b4af9f00-34b7-11eb-8b09-e3602403af60.png)
