### ISSUE TITLE
BUG - Error Getting Transaction Data is displayed in RequestHistory table when a Risk Filter is applied

### ISSUE THREAD

**Issue by werzl** [filetrust/icap-management-ui#83]
"Not sure where the problem lies but on the Mgt UI Request History Page
when only a time filter is applied, and there are no transaction, No Transaction Data Found is displayed
when a filetype filter is applied, and there are no transaction, No Transaction Data Found is displayed
when a Risk filter is applied, and there are no transactions, Error Getting Transaction Data is displayed"

**Comment by werzl** [comment]
Policy management Api is returning a 400 when receiving the following data from the UI
```
{
    "Filter": {
        "TimestampRangeStart": "2021-01-06T10:45:45.659Z",
        "TimestampRangeEnd": "2021-01-06T11:45:45.659Z",
        "Risks": [
            "BlockedByNCFS"
        ],
        "FileTypes": []
    }
}
```

Response: 
```
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "|bdbb6ef1-4034ccaa54d0d7ae.",
    "errors": {
        "request": [
            "The request field is required."
        ],
        "$.Filter.Risks[0]": [
            "The JSON value could not be converted to System.Collections.Generic.List`1[Glasswall.Administration.K8.TransactionEventApi.Common.Enums.Risk]. Path: $.Filter.Risks[0] | LineNumber: 5 | BytePositionInLine: 27."
        ]
    }
}
```

**Comment by asloman** [comment]
Checked on local deployment.

Reproduction steps:
- Navigate to Request history page
- Apply a risk filter

Expected Results:
The filter is applied correctly, and results are displayed (and no transaction data is displayed if there is no transaction data)
Actual Results:
The filter is applied correctly, and results are displayed (and no transaction data is displayed if there is no transaction data)
