### ISSUE TITLE
BUG - If an Error is Thrown While Getting the Server Version - the Navbar Displays the Character 'v'

### ISSUE THREAD

**Issue by werzl** [filetrust/icap-management-ui#99]

**Comment by asloman** [comment]
Reproduction steps:
Navigate to "Network" in Dev tools
Block call called "version"

Expected Results: The version is not displayed
Actual Results: The letter "v" is displayed where the version would be displayed

**Comment by asloman** [comment]
Taken a pull of dev to QA.
Steps followed:
Navigate to "Network" in Dev tools
Block call called "version"

Expected Results: The version is not displayed
Actual Results: The version is not displayed
